# Generated by Django 4.0.6 on 2022-08-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('--', '-----'), ('MR', 'Monsieur'), ('MS', 'Madame')], default='MR', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
