# Generated by Django 4.0.6 on 2022-08-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.PositiveIntegerField(default=7000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'Monsieur'), ('MS', 'Madame')], max_length=2),
        ),
    ]
