# Generated by Django 4.0.6 on 2022-08-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_user_address_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cleo_license',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
