# Generated by Django 4.0.6 on 2022-08-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_website', '0002_alter_customuserprofile_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
